Gomfile
workflow.go

Previously, this warning outputted:
Sleeping for:  5s  seconds. Received 429 HTTP status
It will now output:
Sleeping for: 5s. Received 429 HTTP status
Go's `time.Duration` type automatically includes a `s` unit when
printed.
Also, use `log.Warningf()` rather than `log.Warningln()` for neatness.

Tidy up sleep warning

---

queue/queue_connection.go
queue/queue_connection_test.go
queue/queue_manager.go

Similar to 6d64219c, rename the struct to make it less awkward when
qualified with its package name, `queue`.
Renaming this causes some ambiguity in `workflow_test.go` because the
`queue` package's exported identifiers have been imported into the test
source file and, as such, are accessed without the qualifying `queue`
prefix. But I think that's a smell that we should fix at some point.

Rename queue.QueueConnection to queue.Connection

---

.travis.yml
README.md

Upgrade the Go version we test to 1.4 and remove versions 1.2 and 1.3
from the matrix build.
I don't see the value in testing older Go versions since:
a) supporting multiple versions of Go in Production (generally) is less of an issue
compared to interpreted languages since it compiles to a binary
b) Go's [compatability promise][] means that newer versions in the 1.x
branch should not break backwards-compatibility, so there's little
reason not to use the latest version
[compatability promise]: https://golang.org/doc/go1compat

Upgrade Go to version 1.4

---

crawler_message_item.go
crawler_message_item_test.go
http_crawler/crawler.go
http_crawler/crawler_response.go
http_crawler/crawler_response_test.go
http_crawler/crawler_test.go
main.go
workflow.go
workflow_test.go

We have 2 hostnames, one that we serve the site on and one which is used for assets. We'd like to crawl URLs from both hostnames and store them in separate places on disk.
---
Lots of people have worked on this but I've tried to split it out into a few small commits so it looks like it's only me. Sorry!

[#58334884] Support multiple rootURLs

---

Gomfile
main.go

Use Logrus' hook feature to send exceptions to an Airbrake-compatible
endpoint.

[#76800642] Log exceptions to an Airbrake endpoint

---

.travis.yml

...which provides faster start times.
I also believe it's less commonly used, so may mean that our builds are
in less contention (and thus complete faster).

Use Travis' container-based CI infrastructure

---

Gomfile
main.go

The previous hook used to send exceptions to Errbit's
Airbrake-compatible API was raising errors because we weren't adding an
'error' field to each log entry:
{"endpoint":"https://errbit.preview.alphagov.co.uk","level":"warning","msg":"Exceptions sent to Airbrake must have an 'error' key with the error","source":"airbrake","time":"2015-03-09T11:20:55Z"}
I wrote an integration test for the previous hook which documents this
behaviour:
https://github.com/Sirupsen/logrus/pull/145/files#diff-b9bcfed63bb364328842ba8e05acaa26R46
The previous hook is useful if you need to pass an error type to Errbit,
but in our case we only need to send the error message. I raised a PR
upstream to implement a new hook:
Sirupsen/logrus#146
This commit updates the version of the logrus package we're using to
pull …

[#76800642] Use new Logrus hook to send exceptions to Errbit

---

http_crawler/crawler_response.go
http_crawler/crawler_response_test.go

We don't want the crawler to crawl RSS or ATOM feeds because we don't want to serve old or outdated copies of feeds to feed readers when the site is offline.
It's better for feed readers to receive 5xx responses to indicate things are broken. They'll retry updating feeds later.

Reject ATOM feeds

---

http_crawler/crawler.go
http_crawler/crawler_test.go
main.go
util/util_test.go
workflow_test.go

We want to be able to set the "Rate-Limit-Token" parameter so our stack doesn't rate limit requests from the crawler, which may cause incorrect results being sent to our mirrors.

Add rateLimitToken parameter

---

Makefile

Using Godep requires that we build the app from within a correctly structured [workspace](https://golang.org/doc/code.html#Workspaces).  This is primarily managed by the CI Jenkins job, and this change gives the option for placing the built binary somewhere specific.

Clean up the Makefile

---

health_check.go
health_check_test.go
healthcheck/health_check.go
healthcheck/health_check_test.go

The original trigger for this was that this healtcheck was failing to return on integration, so we needed some way of identifying which check was blocking.  In doing this, I've also taken the opportunity to better encapsulate the process of health-checking.
* A new `healthcheck` package has been created which encapsulates all the generic healthchecking behaviour such as registering and running checks, serialisation of responses, and exposing an HTTPHandler func.
* All checks are now performed in parallel, and with an optional timeout (defaulting to 1 second) on each so if a check takes longer than this
* The individual checks for this application (Redis, RabbitMQ producer, and RabbitMQ consumer) are now individual types which satisfy the new `healthcheck.Checker` interface.
* The output …

Update /healthcheck to provide better encapsulation and more information

---

.travis.yml
README.md

This tidies up a few old version and `gom` references. We're on 1.7.1 now and don't use `gom`.

Fixup some go version things

---

crawler_message_item.go
crawler_message_item_test.go

This is converting valid URI's into invalid ones by introducing UTF-8
characters into them.
This changes the behaviour so that we request valid URI's and then we
decode them when the files are saved to disk.
The prompt for this change was many (~4000 a day) errors logged in Whitehall
that originated from UTF-8 requests and Ruby Unicorns inconsistent
handling of them. See https://github.com/alphagov/slimmer/pull/182 for
more info.

Stop decoding URI's before requesting them.

---

Jenkinsfile

Previously the new style build tag (timestamp + SHA) was only available
by viewing the build logs. This updates the display name to contain it,
as well as the normal build number.
This means that regardless of which method is being used for deployments
both can be accessed.

Add new build tag to display name

---

Jenkinsfile

This means the CAP deployment using S4 will be able to find the file using the
standard release tabgging.
https://trello.com/c/brHYjFnG/83-mirrorer-queue-duplication

Revert to standard build numbering

---

workflow.go

This was incorrectly removed in a previous commit
https://trello.com/c/brHYjFnG/83-mirrorer-queue-duplication

Ensure we ACK rabbit messages

---

main.go
workflow.go
workflow_test.go

The files are saved without query params as such processing URLs that contain them results in a the rendered view being what was generated from the last processed set of query params. This can lead to incorrect and inconsistent results.
https://trello.com/c/BBrR21kl/111-ignore-query-params-when-running-mirrorer

Ignore URL’s with query params

---

crawler_message_item.go
workflow.go
workflow_test.go

We have added this to allow the crawler to follow through multiple pages in the
search results, this should help ensure that we archive every page on the site.
We ensure that URL's with a page command are crawled, however we do not write
them to disk.
https://trello.com/c/5Le8O6cb/120-crawl-pages-with-page-param

Process URL that have a page param

---

http_crawler/crawler.go
http_crawler/crawler_test.go
workflow.go
workflow_test.go

This commit adds the functionality for the crawler to follow redirects when it receives a HTTP 301, 302, 303 or 307 status code for a crawled URL.
A synthetic HTML response with a meta redirect tag is returned, which prompts the crawler to create a file containing this HTML (allowing redirects to work when serving statically) and also adds the destination URL to the list of URLs to be crawled (allowing the content at the eventual destination to be saved).

Follow redirects and create a trail for static serving

---

http_crawler/crawler_response.go

The crawler seems to be missing some js file, this is testing a
theory that this could be due to wrong mime type.

Change javascript mime from x-javascript to javascript

---

Jenkinsfile

Trello: https://trello.com/c/amnaU0V9/853-decommission-the-publishing-end-to-end-tests
As per: https://github.com/alphagov/govuk-jenkinslib/commit/99e8541c7a44c7cfebff0da171b3643573ad869b

Replace deprecated deployIntegration function
